  # You may pin to the exact commit or the version.
  # uses: maierj/fastlane-action@5a3b971aaa26776459bb26894d6c1a1a84a311a7
uses: maierj/fastlane-action@v3.1.0
with:
  # The lane that should be executed.
  lane: 
  # The relative path from the project root directory to the subdirectory where the fastlane folder is located.
  subdirectory: # optional
  # If set to true, adds the verbose option to the fastlane command for extended log output.
  verbose: # optional
  # The options that should be passed as arguments to the lane. The options should be serialized as a JSON object.
  options: # optional
  # The env value that should be passed as an argument to the lane. The value should match to one of your fastlane env files.
  env: # optional
          
